"""empty message

Revision ID: a4feae039794
Revises: eac570fb8dab
Create Date: 2023-11-21 16:52:30.496580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4feae039794'
down_revision: Union[str, None] = 'eac570fb8dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverts', sa.Column('slug', sa.VARCHAR(length=128), nullable=True))
    op.create_unique_constraint(None, 'adverts', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'adverts', type_='unique')
    op.drop_column('adverts', 'slug')
    # ### end Alembic commands ###
