"""empty message

Revision ID: eac570fb8dab
Revises: 
Create Date: 2023-11-21 16:08:41.362633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac570fb8dab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=32), nullable=False),
    sa.CheckConstraint("slug not like '%% %%'"),
    sa.CheckConstraint('length(name) >= 2'),
    sa.CheckConstraint('length(slug) >= 2'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('adverts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('body', sa.VARCHAR(length=250), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('category_id', sa.SMALLINT(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('length(body) >= 50'),
    sa.CheckConstraint('length(title) >= 2'),
    sa.CheckConstraint('price > 0'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adverts')
    op.drop_table('categories')
    # ### end Alembic commands ###
